// Auto-generated by split-i18n.js — Prompt B
// Lang: en — Namespace: customers
// 12 keys

const dict: Record<string, string> = {
  "Bạn có chắc chắn muốn xóa khách hàng này?": "You have chắc chắn muốn delete customer customer/order này?",
  "Bắt đầu bằng cách thêm khách hàng mới": "Start by adding a new customer",
  "Chọn khách này": "Chọn customer này",
  "Cập nhật khách hàng thành công": "Customer updated successfully",
  "Không có khách hàng nào cần xử lý": "Không have customer customer/order nào cần xử lý",
  "Không thể xóa khách hàng": "Không thể delete customer customer/order",
  "Sửa thông tin khách hàng": "Edit customer information",
  "Thêm khách hàng": "Add customer",
  "Tên khách hàng": "Customer name",
  "Tìm kiếm khách hàng...": "Tìm kiếm customer customer/order...",
  "Xóa khách hàng": "Delete customer",
  "Xóa khách hàng thành công": "Customer deleted successfully",
};

export default dict;
