// Auto-generated by split-i18n.js — Prompt B
// Lang: en — Namespace: marketing
// 29 keys

const dict: Record<string, string> = {
  "Bạn có chắc muốn xóa báo cáo này?": "You have chắc muốn delete báo cáo này?",
  "Chi tiết Lead": "Chi tiết Lead",
  "Chọn Facebook Page": "Chọn Facebook Page",
  "Chọn Facebook Page (để trống = toàn team)": "Chọn Facebook Page (để trống = toàn team)",
  "Chọn Marketing": "Chọn Marketing",
  "Chọn nhân viên MKT": "Chọn nhân viên MKT",
  "Chọn nhân viên marketing": "Chọn nhân viên marketing",
  "Cập nhật báo cáo thành công": "Cập nhật báo cáo success",
  "Không thể cập nhật báo cáo": "Không thể update báo cáo",
  "Không thể thêm báo cáo": "Không thể add báo cáo",
  "Không thể xóa báo cáo": "Không thể delete báo cáo",
  "Lỗi khi tải danh sách Facebook Pages": "Lỗi khi load list Facebook Pages",
  "Ngày báo cáo": "Ngày báo cáo",
  "Sửa Lead": "Sửa Lead",
  "Sửa báo cáo Ads": "Sửa báo cáo Ads",
  "Sửa báo cáo chi phí": "Sửa báo cáo chi fee",
  "Sửa thông tin Lead": "Sửa information Lead",
  "Thêm Lead": "Thêm Lead",
  "Thêm báo cáo": "Thêm báo cáo",
  "Thêm báo cáo Ads": "Thêm báo cáo Ads",
  "Tạo báo cáo chi phí": "Tạo báo cáo chi fee",
  "Xác nhận xóa Lead": "Xác nhận delete Lead",
  "Xóa báo cáo?": "Xóa báo cáo?",
  "Đã cập nhật báo cáo thành công!": "Already update báo cáo success!",
  "Đã thêm báo cáo thành công!": "Already add báo cáo success!",
  "Đã xóa báo cáo thành công!": "Already delete báo cáo success!",
  "Đã xảy ra lỗi khi cập nhật báo cáo": "Already xảy ra error khi update báo cáo",
  "Đã xảy ra lỗi khi thêm báo cáo": "Already xảy ra error khi add báo cáo",
  "Đã xảy ra lỗi khi xóa báo cáo": "Already xảy ra error khi delete báo cáo",
};

export default dict;
