// Auto-generated by split-i18n.js — Prompt B
// Lang: en — Namespace: orders
// 24 keys

const dict: Record<string, string> = {
  "Bạn có chắc chắn muốn xóa đơn hàng này?": "Are you sure you want to delete this order?",
  "Chi tiết đơn hàng": "Order details",
  "Chọn combo để thêm vào đơn hàng": "Select a combo to add to the order",
  "Cập nhật tỷ giá": "Update exchange rate",
  "Cập nhật đơn hàng thành công": "Order updated successfully",
  "Cập nhật đơn hàng thất bại": "Failed to update order",
  "Không có đơn hàng": "No orders",
  "Không có đơn hàng nào cần xuất kho": "No orders need to be shipped",
  "Không thể xóa đơn hàng": "Cannot delete order",
  "Không tìm thấy đơn hàng nào phù hợp với bộ lọc": "No orders match the current filters",
  "Lưu tỷ giá": "Save exchange rate",
  "Mã đơn": "Order code",
  "Mã đơn hàng": "Order code",
  "Mỗi đơn hàng đã snapshot tỷ giá": "Each order captures the exchange rate at creation time",
  "Sửa đơn hàng": "Edit order",
  "Trạng thái đơn hàng": "Order status",
  "X đơn cũ hơn — mở trang khách để xem →": "X older orders — open customer page to view →",
  "Xóa đơn hàng": "Delete order",
  "Xóa đơn hàng thành công": "Order deleted successfully",
  "Xóa đơn hàng thất bại": "Failed to delete order",
  "Đang xóa đơn hàng...": "Deleting order...",
  "Đã cập nhật tỷ giá": "Exchange rate updated",
  "Đã thêm đơn hàng thủ công": "Manually added order",
  "Đã tạo X đơn hàng (X khách mới)": "Created X orders (X new customers)",
};

export default dict;
