// Auto-generated by split-i18n.js — Prompt B
// Lang: en — Namespace: sale
// 9 keys

const dict: Record<string, string> = {
  "Chọn Sale": "Chọn Sale",
  "Chọn nhân viên Sale": "Chọn nhân viên Sale",
  "Chọn nhân viên Sale:": "Chọn nhân viên Sale:",
  "Không thể tải danh sách Sale": "Không thể load list Sale",
  "Không thể tải danh sách nhân viên Sale": "Không thể load list nhân viên Sale",
  "Lỗi kết nối khi tải danh sách Sale": "Lỗi kết nối khi load list Sale",
  "Ngày phân công": "Ngày phân công",
  "Xác nhận phân công hàng loạt": "Xác nhận phân công customer/order loạt",
  "Đang tải danh sách Sale...": "Đang load list Sale...",
};

export default dict;
