// Auto-generated by split-i18n.js — Prompt B
// Lang: en — Namespace: settings
// 4 keys

const dict: Record<string, string> = {
  "Giá & Tỷ giá": "Giá & Tỷ price",
  "Không thể làm mới thông báo": "Không thể làm mới thông báo",
  "Không thể tải thông báo": "Không thể load thông báo",
  "Đã xóa thông báo thành công": "Already delete thông báo success",
};

export default dict;
