// Auto-generated by split-i18n.js — Prompt B
// Lang: en — Namespace: status
// 34 keys

const dict: Record<string, string> = {
  "Bản nháp": "Bản nháp",
  "Bị từ chối": "Bị từ chối",
  "Chờ duyệt": "Chờ duyệt",
  "Chờ thanh toán": "Chờ thanh toán",
  "Chờ xác nhận": "Waiting for confirmation",
  "Chờ xử lý": "Chờ xử lý",
  "Cảnh báo": "Cảnh báo",
  "Giao thất bại": "Giao failed",
  "Hoạt động": "Hoạt động",
  "Khách hàng bị xóa": "Khách customer/order bị delete",
  "Không hoạt động": "Không hoạt động",
  "Không mua": "Không mua",
  "Không nghe máy": "Không nghe máy",
  "Lỗi": "Lỗi",
  "Mới": "Mới",
  "Sale bị hủy gán": "Sale bị cancel gán",
  "Tiềm năng": "Tiềm năng",
  "Tắt": "Tắt",
  "Từ chối": "Từ chối",
  "cancelled": "Cancelled",
  "Đang đóng gói": "Packing",
  "Đã chốt": "Already chốt",
  "Đã giao": "Already giao",
  "Đã giao hàng": "Delivered",
  "Đã hoàn": "Returned",
  "Đã hoàn trả": "Already return trả",
  "Đã hủy": "Cancelled",
  "Đã liên hệ": "Already liên hệ",
  "Đã phân công": "Already phân công",
  "Đã tạo đơn": "Already create order",
  "Đã xác nhận": "Confirmed",
  "Đơn hàng bị hủy": "Đơn customer/order bị cancel",
  "Đủ điều kiện": "Đủ điều kiện",
  "✓ Đã tạo": "✓ Already create",
};

export default dict;
