// Auto-generated by split-i18n.js — Prompt B
// Lang: en — Namespace: warehouse
// 23 keys

const dict: Record<string, string> = {
  "Chi tiết tài khoản": "Chi tiết tài warehouseản",
  "Chọn kho": "Chọn warehouse",
  "Chọn kho nguồn": "Chọn warehouse source",
  "Chọn kho đích": "Chọn warehouse đích",
  "Cập nhật tài khoản": "Cập nhật tài warehouseản",
  "Cập nhật tài khoản thành công": "Account updated successfully",
  "Danh sách mặt hàng điều chỉnh": "Danh sách mặt customer/order điều chỉnh",
  "Không có dữ liệu tồn kho": "Không have dữ liệu tồn warehouse",
  "Không thể cập nhật kho": "Không thể update warehouse",
  "Không thể nhập kho": "Không thể enter warehouse",
  "Không thể nhập kho. Vui lòng thử lại.": "Không thể enter warehouse. Please thử lại.",
  "Không thể tải kho": "Không thể load warehouse",
  "Không thể xóa kho": "Không thể delete warehouse",
  "Không tải được danh sách kho": "Không load be list warehouse",
  "Lưu điều chỉnh": "Lưu điều chỉnh",
  "Ngày đáp kho": "Ngày đáp warehouse",
  "Số lượng phải trong khoảng 1–100,000": "Số lượng phải trong warehouseảng 1–100,000",
  "Số lượng điều chỉnh": "Số lượng điều chỉnh",
  "Sửa số lượng tồn kho": "Sửa quantity tồn warehouse",
  "Tạo tài khoản mới": "Tạo tài warehouseản mới",
  "Xác nhận xuất kho": "Xác nhận export warehouse",
  "Đang tải tồn kho...": "Đang load tồn warehouse...",
  "Đã thêm tài khoản, đang tải lại sơ đồ…": "Already add tài warehouseản, is load lại sơ đồ…",
};

export default dict;
