// Auto-generated by split-i18n.js — Prompt B
// Loader trung tâm cho cả 3 ngôn ngữ.

import vi from "./vi";
import en from "./en";
import mn from "./mn";

import type { Language } from "@/store/language.store";

type Dict = Record<string, string>;

const DICT: Record<Language, Dict> = {
  vi: vi as Dict,
  en: en as Dict,
  mn: mn as Dict,
};

export function getDict(lang: Language): Dict {
  return DICT[lang] ?? DICT.vi;
}

export function getAllDicts(): Record<Language, Dict> {
  return DICT;
}

export default DICT;
