// Auto-generated by split-i18n.js — Prompt B
// Lang: mn — Namespace: accounts
// 10 keys

const dict: Record<string, string> = {
  "Chọn khu vực": "Бүс сонгох",
  "Chọn leader": "Удирдагч сонгох",
  "Chọn nhân viên": "Ажилтан сонгох",
  "Chọn phòng ban": "Тасаг сонгох",
  "Chọn team": "Баг сонгох",
  "Không có avatar": "Аватар байхгүй",
  "Không thể tải sơ đồ tổ chức": "Байгууллагын схем ачаалах боломжгүй",
  "Không thể xóa ảnh": "Зураг устгах боломжгүй",
  "Tìm kiếm leader": "Leader хайх",
  "Tải lên avatar": "Аватар upload хийх",
};

export default dict;
