// Auto-generated by split-i18n.js — Prompt B
// Lang: mn — Namespace: customers
// 12 keys

const dict: Record<string, string> = {
  "Bạn có chắc chắn muốn xóa khách hàng này?": "Энэ харилцагчийг устгахдаа итгэлтэй байна уу?",
  "Bắt đầu bằng cách thêm khách hàng mới": "Шинэ харилцагч нэмэхээр эхлэнэ үү",
  "Chọn khách này": "Энэ харилцагчийг сонгох",
  "Cập nhật khách hàng thành công": "Харилцагчийн мэдээлэл шинэчлэгдлээ",
  "Không có khách hàng nào cần xử lý": "Боловсруулах харилцагч байхгүй",
  "Không thể xóa khách hàng": "Харилцагч устгах боломжгүй",
  "Sửa thông tin khách hàng": "Харилцагчийн мэдээлэл засах",
  "Thêm khách hàng": "Харилцагч нэмэх",
  "Tên khách hàng": "Харилцагчийн нэр",
  "Tìm kiếm khách hàng...": "Харилцагч хайх...",
  "Xóa khách hàng": "Харилцагч устгах",
  "Xóa khách hàng thành công": "Харилцагч устгагдлаа",
};

export default dict;
