// Auto-generated by split-i18n.js — Prompt B
// Lang: mn — gộp 12 namespace, 463 keys

import navigation from "./navigation";
import validation from "./validation";
import status from "./status";
import orders from "./orders";
import products from "./products";
import customers from "./customers";
import warehouse from "./warehouse";
import marketing from "./marketing";
import sale from "./sale";
import accounts from "./accounts";
import settings from "./settings";
import common from "./common";

const dict: Record<string, string> = {
  ...navigation,
  ...validation,
  ...status,
  ...orders,
  ...products,
  ...customers,
  ...warehouse,
  ...marketing,
  ...sale,
  ...accounts,
  ...settings,
  ...common,
};

export default dict;
