// Auto-generated by split-i18n.js — Prompt B
// Lang: mn — Namespace: marketing
// 29 keys

const dict: Record<string, string> = {
  "Bạn có chắc muốn xóa báo cáo này?": "Энэ тайланг устгахдаа итгэлтэй байна уу?",
  "Chi tiết Lead": "Lead-ийн дэлгэрэнгүй",
  "Chọn Facebook Page": "Facebook Page сонгох",
  "Chọn Facebook Page (để trống = toàn team)": "Facebook Page сонгох (хоосон = бүх баг)",
  "Chọn Marketing": "Маркетинг сонгох",
  "Chọn nhân viên MKT": "MKT ажилтан сонгох",
  "Chọn nhân viên marketing": "Маркетинг ажилтан сонгох",
  "Cập nhật báo cáo thành công": "Тайлан амжилттай шинэчлэгдлээ",
  "Không thể cập nhật báo cáo": "Тайлан шинэчлэх боломжгүй",
  "Không thể thêm báo cáo": "Тайлан нэмэх боломжгүй",
  "Không thể xóa báo cáo": "Тайлан устгах боломжгүй",
  "Lỗi khi tải danh sách Facebook Pages": "Facebook Pages жагсаалт ачаалах үед алдаа",
  "Ngày báo cáo": "Тайлангийн огноо",
  "Sửa Lead": "Lead засах",
  "Sửa báo cáo Ads": "Ads тайлан засах",
  "Sửa báo cáo chi phí": "Зардлын тайлан засах",
  "Sửa thông tin Lead": "Lead-ийн мэдээлэл засах",
  "Thêm Lead": "Lead нэмэх",
  "Thêm báo cáo": "Тайлан нэмэх",
  "Thêm báo cáo Ads": "Ads тайлан нэмэх",
  "Tạo báo cáo chi phí": "Зардлын тайлан үүсгэх",
  "Xác nhận xóa Lead": "Lead устгахыг баталгаажуулах",
  "Xóa báo cáo?": "Тайлан устгах уу?",
  "Đã cập nhật báo cáo thành công!": "Тайлан амжилттай шинэчлэгдлээ!",
  "Đã thêm báo cáo thành công!": "Тайлан амжилттай нэмэгдлээ!",
  "Đã xóa báo cáo thành công!": "Тайлан амжилттай устгагдлаа!",
  "Đã xảy ra lỗi khi cập nhật báo cáo": "Тайлан шинэчлэхэд алдаа гарлаа",
  "Đã xảy ra lỗi khi thêm báo cáo": "Тайлан нэмэхэд алдаа гарлаа",
  "Đã xảy ra lỗi khi xóa báo cáo": "Тайлан устгахад алдаа гарлаа",
};

export default dict;
