// Auto-generated by split-i18n.js — Prompt B
// Lang: mn — Namespace: orders
// 24 keys

const dict: Record<string, string> = {
  "Bạn có chắc chắn muốn xóa đơn hàng này?": "Энэ захиалгыг устгахдаа итгэлтэй байна уу?",
  "Chi tiết đơn hàng": "Захиалгын дэлгэрэнгүй",
  "Chọn combo để thêm vào đơn hàng": "Захиалга руу нэмэх комбо сонгох",
  "Cập nhật tỷ giá": "Валютын ханш шинэчлэх",
  "Cập nhật đơn hàng thành công": "Захиалгын мэдээлэл шинэчлэгдлээ",
  "Cập nhật đơn hàng thất bại": "Захиалгын мэдээлэл шинэчлэхэд алдаа гарлаа",
  "Không có đơn hàng": "Захиалга байхгүй",
  "Không có đơn hàng nào cần xuất kho": "Гаргах захиалга байхгүй",
  "Không thể xóa đơn hàng": "Захиалга устгах боломжгүй",
  "Không tìm thấy đơn hàng nào phù hợp với bộ lọc": "Шүүлтүүрт тохирох захиалга олдсонгүй",
  "Lưu tỷ giá": "Валютын ханш хадгалах",
  "Mã đơn": "Захиалгын код",
  "Mã đơn hàng": "Захиалгын код",
  "Mỗi đơn hàng đã snapshot tỷ giá": "Захиалга бүр валютын ханш snapshot хийгдсэн",
  "Sửa đơn hàng": "Захиалга засах",
  "Trạng thái đơn hàng": "Захиалгын төлөв",
  "X đơn cũ hơn — mở trang khách để xem →": "X хуучин захиалга — харилцагчийн хуудсыг нээж үзэх →",
  "Xóa đơn hàng": "Захиалга устгах",
  "Xóa đơn hàng thành công": "Захиалга устгагдлаа",
  "Xóa đơn hàng thất bại": "Захиалга устгахад алдаа гарлаа",
  "Đang xóa đơn hàng...": "Захиалга устгаж байна...",
  "Đã cập nhật tỷ giá": "Валютын ханш шинэчлэгдлээ",
  "Đã thêm đơn hàng thủ công": "Гар аргаар захиалга нэмэгдлээ",
  "Đã tạo X đơn hàng (X khách mới)": "X захиалга үүсгэгдлээ (X шинэ харилцагч)",
};

export default dict;
