// Auto-generated by split-i18n.js — Prompt B
// Lang: mn — Namespace: sale
// 9 keys

const dict: Record<string, string> = {
  "Chọn Sale": "Sale сонгох",
  "Chọn nhân viên Sale": "Sale ажилтан сонгох",
  "Chọn nhân viên Sale:": "Sale ажилтан сонгох:",
  "Không thể tải danh sách Sale": "Sale жагсаалт ачаалах боломжгүй",
  "Không thể tải danh sách nhân viên Sale": "Sale ажилтан жагсаалт ачаалах боломжгүй",
  "Lỗi kết nối khi tải danh sách Sale": "Sale жагсаалт ачаалах үед холболтын алдаа",
  "Ngày phân công": "Хуваарилсан огноо",
  "Xác nhận phân công hàng loạt": "Масс делегат баталгаажуулах",
  "Đang tải danh sách Sale...": "Sale жагсаалт ачаалж байна...",
};

export default dict;
