// Auto-generated by split-i18n.js — Prompt B
// Lang: mn — Namespace: settings
// 4 keys

const dict: Record<string, string> = {
  "Giá & Tỷ giá": "Үнэ & Валютын ханш",
  "Không thể làm mới thông báo": "Мэдэгдэл дахин хийх боломжгүй",
  "Không thể tải thông báo": "Мэдэгдэл ачаалах боломжгүй",
  "Đã xóa thông báo thành công": "Мэдэгдэл амжилттай устгагдлаа",
};

export default dict;
