// Auto-generated by split-i18n.js — Prompt B
// Lang: mn — Namespace: warehouse
// 23 keys

const dict: Record<string, string> = {
  "Chi tiết tài khoản": "Дансны дэлгэрэнгүй",
  "Chọn kho": "Агуулах сонгох",
  "Chọn kho nguồn": "Эх агуулах сонгох",
  "Chọn kho đích": "Очих агуулах сонгох",
  "Cập nhật tài khoản": "Данс шинэчлэх",
  "Cập nhật tài khoản thành công": "Данс амжилттай шинэчлэгдлээ",
  "Danh sách mặt hàng điều chỉnh": "Тохируулсан барааны жагсаалт",
  "Không có dữ liệu tồn kho": "Үлдэгдэл байхгүй",
  "Không thể cập nhật kho": "Агуулах шинэчлэх боломжгүй",
  "Không thể nhập kho": "Агуулах руу оруулах боломжгүй",
  "Không thể nhập kho. Vui lòng thử lại.": "Агуулах руу оруулах боломжгүй. Дахин оролдоно уу.",
  "Không thể tải kho": "Агуулах ачаалах боломжгүй",
  "Không thể xóa kho": "Агуулах устгах боломжгүй",
  "Không tải được danh sách kho": "Агуулах жагсаалт ачаалах боломжгүй",
  "Lưu điều chỉnh": "Тохиргоо хадгалах",
  "Ngày đáp kho": "Агуулахд ирсэн огноо",
  "Số lượng phải trong khoảng 1–100,000": "Тоо 1-100,000-ийн хооронд байх ёстой",
  "Số lượng điều chỉnh": "Тохируулсан тоо",
  "Sửa số lượng tồn kho": "Үлдэгдэл өөрчлөх",
  "Tạo tài khoản mới": "Шинэ данс үүсгэх",
  "Xác nhận xuất kho": "Бараа гаргахыг баталгаажуулах",
  "Đang tải tồn kho...": "Үлдэгдэл ачаалж байна...",
  "Đã thêm tài khoản, đang tải lại sơ đồ…": "Данс нэмэгдлээ, схем дахин ачаалж байна...",
};

export default dict;
