/**
 * Marketing Dashboard Types (Sprint 5.1 — Marketing Dashboard)
 *
 * Type definitions for the marketing dashboard.
 */

export type MarketingSummary = {
  /** Leads created today */
  todayLead: number;
  /** Leads created this week */
  weekLead: number;
  /** Leads created this month */
  monthLead: number;
  /** Total leads accumulated */
  totalLead: number;
  /** Leads already assigned to a sale */
  assignedLead: number;
  /** Leads converted to orders */
  closedLead: number;
  /** Conversion rate percentage (0–100) */
  conversionRate: number;
};

export type DailyLeadChartItem = {
  /** Date string (YYYY-MM-DD) */
  date: string;
  /** Number of leads on this day */
  count: number;
};

export type LeadSourceChartItem = {
  /** Lead source name */
  source: string;
  /** Number of leads from this source */
  count: number;
};

export type TopMarketingItem = {
  /** Unique employee identifier */
  employeeId: string;
  /** Employee display name */
  employeeName: string;
  /** Avatar URL or null (optional) */
  avatar?: string | null;
  /** Total leads generated by this employee */
  totalLead: number;
  /** Leads converted to orders */
  closedLead: number;
  /** Conversion rate (number, e.g. 25.5 means 25.5%) */
  conversionRate: number;
};

export type MarketingChartData = {
  dailyLead: DailyLeadChartItem[];
  source: LeadSourceChartItem[];
};

export type MarketingDashboardData = {
  summary: MarketingSummary;
  chart: MarketingChartData;
  topMarketing: TopMarketingItem[];
};

export type MarketingDashboardApiResponse = {
  success: boolean;
  data: MarketingDashboardData;
  message?: string;
};