// Auto-generated by split-i18n.js — Prompt B
// Lang: vi — Namespace: accounts
// 10 keys

const dict: Record<string, string> = {
  "Chọn khu vực": "Chọn khu vực",
  "Chọn leader": "Chọn leader",
  "Chọn nhân viên": "Chọn nhân viên",
  "Chọn phòng ban": "Chọn phòng ban",
  "Chọn team": "Chọn team",
  "Không có avatar": "Không có avatar",
  "Không thể tải sơ đồ tổ chức": "Không thể tải sơ đồ tổ chức",
  "Không thể xóa ảnh": "Không thể xóa ảnh",
  "Tìm kiếm leader": "Tìm kiếm leader",
  "Tải lên avatar": "Tải lên avatar",
};

export default dict;
