// Auto-generated by split-i18n.js — Prompt B
// Lang: vi — Namespace: customers
// 12 keys

const dict: Record<string, string> = {
  "Bạn có chắc chắn muốn xóa khách hàng này?": "Bạn có chắc chắn muốn xóa khách hàng này?",
  "Bắt đầu bằng cách thêm khách hàng mới": "Bắt đầu bằng cách thêm khách hàng mới",
  "Chọn khách này": "Chọn khách này",
  "Cập nhật khách hàng thành công": "Cập nhật khách hàng thành công",
  "Không có khách hàng nào cần xử lý": "Không có khách hàng nào cần xử lý",
  "Không thể xóa khách hàng": "Không thể xóa khách hàng",
  "Sửa thông tin khách hàng": "Sửa thông tin khách hàng",
  "Thêm khách hàng": "Thêm khách hàng",
  "Tên khách hàng": "Tên khách hàng",
  "Tìm kiếm khách hàng...": "Tìm kiếm khách hàng...",
  "Xóa khách hàng": "Xóa khách hàng",
  "Xóa khách hàng thành công": "Xóa khách hàng thành công",
};

export default dict;
