// Auto-generated by split-i18n.js — Prompt B
// Lang: vi — Namespace: marketing
// 29 keys

const dict: Record<string, string> = {
  "Bạn có chắc muốn xóa báo cáo này?": "Bạn có chắc muốn xóa báo cáo này?",
  "Chi tiết Lead": "Chi tiết Lead",
  "Chọn Facebook Page": "Chọn Facebook Page",
  "Chọn Facebook Page (để trống = toàn team)": "Chọn Facebook Page (để trống = toàn team)",
  "Chọn Marketing": "Chọn Marketing",
  "Chọn nhân viên MKT": "Chọn nhân viên MKT",
  "Chọn nhân viên marketing": "Chọn nhân viên marketing",
  "Cập nhật báo cáo thành công": "Cập nhật báo cáo thành công",
  "Không thể cập nhật báo cáo": "Không thể cập nhật báo cáo",
  "Không thể thêm báo cáo": "Không thể thêm báo cáo",
  "Không thể xóa báo cáo": "Không thể xóa báo cáo",
  "Lỗi khi tải danh sách Facebook Pages": "Lỗi khi tải danh sách Facebook Pages",
  "Ngày báo cáo": "Ngày báo cáo",
  "Sửa Lead": "Sửa Lead",
  "Sửa báo cáo Ads": "Sửa báo cáo Ads",
  "Sửa báo cáo chi phí": "Sửa báo cáo chi phí",
  "Sửa thông tin Lead": "Sửa thông tin Lead",
  "Thêm Lead": "Thêm Lead",
  "Thêm báo cáo": "Thêm báo cáo",
  "Thêm báo cáo Ads": "Thêm báo cáo Ads",
  "Tạo báo cáo chi phí": "Tạo báo cáo chi phí",
  "Xác nhận xóa Lead": "Xác nhận xóa Lead",
  "Xóa báo cáo?": "Xóa báo cáo?",
  "Đã cập nhật báo cáo thành công!": "Đã cập nhật báo cáo thành công!",
  "Đã thêm báo cáo thành công!": "Đã thêm báo cáo thành công!",
  "Đã xóa báo cáo thành công!": "Đã xóa báo cáo thành công!",
  "Đã xảy ra lỗi khi cập nhật báo cáo": "Đã xảy ra lỗi khi cập nhật báo cáo",
  "Đã xảy ra lỗi khi thêm báo cáo": "Đã xảy ra lỗi khi thêm báo cáo",
  "Đã xảy ra lỗi khi xóa báo cáo": "Đã xảy ra lỗi khi xóa báo cáo",
};

export default dict;
