// Auto-generated by split-i18n.js — Prompt B
// Lang: vi — Namespace: orders
// 24 keys

const dict: Record<string, string> = {
  "Bạn có chắc chắn muốn xóa đơn hàng này?": "Bạn có chắc chắn muốn xóa đơn hàng này?",
  "Chi tiết đơn hàng": "Chi tiết đơn hàng",
  "Chọn combo để thêm vào đơn hàng": "Chọn combo để thêm vào đơn hàng",
  "Cập nhật tỷ giá": "Cập nhật tỷ giá",
  "Cập nhật đơn hàng thành công": "Cập nhật đơn hàng thành công",
  "Cập nhật đơn hàng thất bại": "Cập nhật đơn hàng thất bại",
  "Không có đơn hàng": "Không có đơn hàng",
  "Không có đơn hàng nào cần xuất kho": "Không có đơn hàng nào cần xuất kho",
  "Không thể xóa đơn hàng": "Không thể xóa đơn hàng",
  "Không tìm thấy đơn hàng nào phù hợp với bộ lọc": "Không tìm thấy đơn hàng nào phù hợp với bộ lọc",
  "Lưu tỷ giá": "Lưu tỷ giá",
  "Mã đơn": "Mã đơn",
  "Mã đơn hàng": "Mã đơn hàng",
  "Mỗi đơn hàng đã snapshot tỷ giá": "Mỗi đơn hàng đã snapshot tỷ giá",
  "Sửa đơn hàng": "Sửa đơn hàng",
  "Trạng thái đơn hàng": "Trạng thái đơn hàng",
  "X đơn cũ hơn — mở trang khách để xem →": "X đơn cũ hơn — mở trang khách để xem →",
  "Xóa đơn hàng": "Xóa đơn hàng",
  "Xóa đơn hàng thành công": "Xóa đơn hàng thành công",
  "Xóa đơn hàng thất bại": "Xóa đơn hàng thất bại",
  "Đang xóa đơn hàng...": "Đang xóa đơn hàng...",
  "Đã cập nhật tỷ giá": "Đã cập nhật tỷ giá",
  "Đã thêm đơn hàng thủ công": "Đã thêm đơn hàng thủ công",
  "Đã tạo X đơn hàng (X khách mới)": "Đã tạo X đơn hàng (X khách mới)",
};

export default dict;
