// Auto-generated by split-i18n.js — Prompt B
// Lang: vi — Namespace: sale
// 9 keys

const dict: Record<string, string> = {
  "Chọn Sale": "Chọn Sale",
  "Chọn nhân viên Sale": "Chọn nhân viên Sale",
  "Chọn nhân viên Sale:": "Chọn nhân viên Sale:",
  "Không thể tải danh sách Sale": "Không thể tải danh sách Sale",
  "Không thể tải danh sách nhân viên Sale": "Không thể tải danh sách nhân viên Sale",
  "Lỗi kết nối khi tải danh sách Sale": "Lỗi kết nối khi tải danh sách Sale",
  "Ngày phân công": "Ngày phân công",
  "Xác nhận phân công hàng loạt": "Xác nhận phân công hàng loạt",
  "Đang tải danh sách Sale...": "Đang tải danh sách Sale...",
};

export default dict;
