// Auto-generated by split-i18n.js — Prompt B
// Lang: vi — Namespace: settings
// 4 keys

const dict: Record<string, string> = {
  "Giá & Tỷ giá": "Giá & Tỷ giá",
  "Không thể làm mới thông báo": "Không thể làm mới thông báo",
  "Không thể tải thông báo": "Không thể tải thông báo",
  "Đã xóa thông báo thành công": "Đã xóa thông báo thành công",
};

export default dict;
