// Auto-generated by split-i18n.js — Prompt B
// Lang: vi — Namespace: status
// 34 keys

const dict: Record<string, string> = {
  "Bản nháp": "Bản nháp",
  "Bị từ chối": "Bị từ chối",
  "Chờ duyệt": "Chờ duyệt",
  "Chờ thanh toán": "Chờ thanh toán",
  "Chờ xác nhận": "Chờ xác nhận",
  "Chờ xử lý": "Chờ xử lý",
  "Cảnh báo": "Cảnh báo",
  "Giao thất bại": "Giao thất bại",
  "Hoạt động": "Hoạt động",
  "Khách hàng bị xóa": "Khách hàng bị xóa",
  "Không hoạt động": "Không hoạt động",
  "Không mua": "Không mua",
  "Không nghe máy": "Không nghe máy",
  "Lỗi": "Lỗi",
  "Mới": "Mới",
  "Sale bị hủy gán": "Sale bị hủy gán",
  "Tiềm năng": "Tiềm năng",
  "Tắt": "Tắt",
  "Từ chối": "Từ chối",
  "cancelled": "cancelled",
  "Đang đóng gói": "Đang đóng gói",
  "Đã chốt": "Đã chốt",
  "Đã giao": "Đã giao",
  "Đã giao hàng": "Đã giao hàng",
  "Đã hoàn": "Đã hoàn",
  "Đã hoàn trả": "Đã hoàn trả",
  "Đã hủy": "Đã hủy",
  "Đã liên hệ": "Đã liên hệ",
  "Đã phân công": "Đã phân công",
  "Đã tạo đơn": "Đã tạo đơn",
  "Đã xác nhận": "Đã xác nhận",
  "Đơn hàng bị hủy": "Đơn hàng bị hủy",
  "Đủ điều kiện": "Đủ điều kiện",
  "✓ Đã tạo": "✓ Đã tạo",
};

export default dict;
