// Auto-generated by split-i18n.js — Prompt B
// Lang: vi — Namespace: warehouse
// 23 keys

const dict: Record<string, string> = {
  "Chi tiết tài khoản": "Chi tiết tài khoản",
  "Chọn kho": "Chọn kho",
  "Chọn kho nguồn": "Chọn kho nguồn",
  "Chọn kho đích": "Chọn kho đích",
  "Cập nhật tài khoản": "Cập nhật tài khoản",
  "Cập nhật tài khoản thành công": "Cập nhật tài khoản thành công",
  "Danh sách mặt hàng điều chỉnh": "Danh sách mặt hàng điều chỉnh",
  "Không có dữ liệu tồn kho": "Không có dữ liệu tồn kho",
  "Không thể cập nhật kho": "Không thể cập nhật kho",
  "Không thể nhập kho": "Không thể nhập kho",
  "Không thể nhập kho. Vui lòng thử lại.": "Không thể nhập kho. Vui lòng thử lại.",
  "Không thể tải kho": "Không thể tải kho",
  "Không thể xóa kho": "Không thể xóa kho",
  "Không tải được danh sách kho": "Không tải được danh sách kho",
  "Lưu điều chỉnh": "Lưu điều chỉnh",
  "Ngày đáp kho": "Ngày đáp kho",
  "Số lượng phải trong khoảng 1–100,000": "Số lượng phải trong khoảng 1–100,000",
  "Số lượng điều chỉnh": "Số lượng điều chỉnh",
  "Sửa số lượng tồn kho": "Sửa số lượng tồn kho",
  "Tạo tài khoản mới": "Tạo tài khoản mới",
  "Xác nhận xuất kho": "Xác nhận xuất kho",
  "Đang tải tồn kho...": "Đang tải tồn kho...",
  "Đã thêm tài khoản, đang tải lại sơ đồ…": "Đã thêm tài khoản, đang tải lại sơ đồ…",
};

export default dict;
